name: iota
channels:
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - applaunchservices=0.2.1=pyhd3eb1b0_0
  - appnope=0.1.2=py39hecd8cb5_1001
  - argh=0.26.2=py39hecd8cb5_0
  - arrow=0.13.1=py39hecd8cb5_0
  - astroid=2.6.6=py39hecd8cb5_0
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.5.7=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py39he3068b8_1
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py39h9ed2024_1003
  - ca-certificates=2021.10.26=hecd8cb5_2
  - certifi=2021.10.8=py39hecd8cb5_0
  - cffi=1.14.6=py39h2125817_0
  - chardet=4.0.0=py39hecd8cb5_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cookiecutter=1.7.2=pyhd3eb1b0_0
  - cryptography=35.0.0=py39h2fd3fbb_0
  - cycler=0.10.0=py39hecd8cb5_0
  - dash=1.19.0=pyhd3eb1b0_0
  - dash-core-components=1.3.1=py_0
  - dash-html-components=1.0.1=py_0
  - dash-renderer=1.1.2=py_0
  - dash-table=4.4.1=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py39he9d5cce_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - docutils=0.17.1=py39hecd8cb5_1
  - entrypoints=0.3=py39hecd8cb5_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - flask-compress=1.5.0=py_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - future=0.18.2=py39hecd8cb5_1
  - giflib=5.2.1=haf1e3a3_0
  - icu=58.2=h0a44026_3
  - idna=3.2=pyhd3eb1b0_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py39hecd8cb5_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - inflection=0.5.1=py39hecd8cb5_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.4.1=py39hecd8cb5_1
  - ipython=7.29.0=py39h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jedi=0.18.0=py39hecd8cb5_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - jpeg=9d=h9ed2024_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py39hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - keyring=23.1.0=py39hecd8cb5_0
  - kiwisolver=1.3.1=py39h23ab428_0
  - lazy-object-proxy=1.6.0=py39h9ed2024_0
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libtiff=4.2.0=h87d7836_0
  - libwebp=1.2.0=hacca55c_0
  - libwebp-base=1.2.0=h9ed2024_0
  - lz4-c=1.9.3=h23ab428_1
  - markupsafe=1.1.1=py39h9ed2024_0
  - matplotlib=3.4.3=py39hecd8cb5_0
  - matplotlib-base=3.4.3=py39h0a11d32_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py39hecd8cb5_1
  - mistune=0.8.4=py39h9ed2024_1000
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py39h9ed2024_0
  - mkl_fft=1.3.1=py39h4ab4a9b_0
  - mkl_random=1.2.2=py39hb2f4e1b_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39hecd8cb5_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - numexpr=2.7.3=py39h5873af2_1
  - numpy=1.21.2=py39h4b4dc7a_0
  - numpy-base=1.21.2=py39he0bd621_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h9ed2024_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.4=py39h743cdd8_0
  - pandocfilters=1.4.3=py39hecd8cb5_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pathspec=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py39h98e4679_0
  - pip=21.2.4=py39hecd8cb5_0
  - plotly=4.14.3=pyhd3eb1b0_0
  - pluggy=1.0.0=py39hecd8cb5_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.8.0=py39h9ed2024_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pylint=2.9.6=py39hecd8cb5_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h23ab428_6
  - pyrsistent=0.18.0=py39hca72f7f_0
  - pysocks=1.7.1=py39hecd8cb5_0
  - python=3.9.7=h88f2d9e_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python.app=3=py39hca72f7f_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py39hca72f7f_1
  - pyzmq=22.2.1=py39h23ab428_1
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h9ed2024_0
  - regex=2021.8.3=py39h9ed2024_0
  - requests=2.26.0=pyhd3eb1b0_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - rope=0.21.1=pyhd3eb1b0_0
  - rtree=0.9.7=py39hecd8cb5_1
  - setuptools=58.0.4=py39hecd8cb5_0
  - sip=4.19.13=py39h23ab428_0
  - six=1.16.0=pyhd3eb1b0_0
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=4.2.0=pyhd3eb1b0_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py39hecd8cb5_1
  - spyder-kernels=2.1.3=py39hecd8cb5_0
  - sqlite=3.36.0=hce871da_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h7bc2e8c_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py39h9ed2024_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py39h9ed2024_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - ujson=4.0.2=py39h23ab428_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - watchdog=2.1.3=py39hd5f6b7e_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hecd8cb5_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - wrapt=1.12.1=py39h9ed2024_1
  - wurlitzer=2.1.1=py39hecd8cb5_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
  - pip:
    - altgraph==0.17.2
    - macholib==1.15.2
    - pyinstaller==4.7
    - pyinstaller-hooks-contrib==2021.4
    - pyorbital==1.6.1
    - scipy==1.7.3
prefix: /Users/ac5119/opt/anaconda3/envs/iota
